/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Listing {
    id: bigint;
    title: string;
    isPublished: boolean;
    availableQuantity: number;
    createdAt: Time;
    unit: string;
    description: string;
    pricePerUnit: number;
    updatedAt?: Time;
    category: ProductCategory;
    harvestDate?: string;
    location: string;
    farmer: Principal;
}
export interface OrderMessage {
    author: Principal;
    orderId: bigint;
    message: string;
    timestamp: Time;
}
export type ProductCategory = {
    __kind__: "grains";
    grains: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "livestock";
    livestock: null;
} | {
    __kind__: "fruits";
    fruits: null;
} | {
    __kind__: "vegetables";
    vegetables: null;
} | {
    __kind__: "dairy";
    dairy: null;
};
export interface UserProfile {
    bio: string;
    contact?: string;
    displayName: string;
    role: UserRole;
    location: string;
}
export interface OrderRequest {
    id: bigint;
    status: Variant_pending_accepted_declined;
    listingId: bigint;
    note: string;
    createdAt: Time;
    updatedAt?: Time;
    message?: string;
    quantity: number;
    buyer: Principal;
}
export enum UserRole {
    buyer = "buyer",
    farmer = "farmer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_accepted_declined {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptOrderRequest(orderId: bigint): Promise<void>;
    addOrderMessage(orderId: bigint, message: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createListing(listing: Listing): Promise<bigint>;
    declineOrderRequest(orderId: bigint): Promise<void>;
    deleteListing(listingId: bigint): Promise<void>;
    filterListingsByCategory(category: ProductCategory): Promise<Array<Listing>>;
    getAllListings(): Promise<Array<Listing>>;
    getAllProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getBuyerOrderRequests(): Promise<Array<OrderRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getFarmerOrderRequests(): Promise<Array<OrderRequest>>;
    getListingById(id: bigint): Promise<Listing | null>;
    getListingsByFarmer(farmer: Principal): Promise<Array<Listing>>;
    getListingsSorted(sortBy: string): Promise<Array<Listing>>;
    getOrderMessages(orderId: bigint): Promise<Array<OrderMessage>>;
    getOrderRequestsForListing(listingId: bigint): Promise<Array<OrderRequest>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    placeOrderRequest(listingId: bigint, quantity: number, note: string, message: string | null): Promise<bigint>;
    publishListing(listingId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListings(searchTerm: string): Promise<Array<Listing>>;
    unpublishListing(listingId: bigint): Promise<void>;
    updateListing(listingId: bigint, updated: Listing): Promise<void>;
}
import type { Listing as _Listing, OrderRequest as _OrderRequest, ProductCategory as _ProductCategory, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptOrderRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptOrderRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptOrderRequest(arg0);
            return result;
        }
    }
    async addOrderMessage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrderMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrderMessage(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createListing(arg0: Listing): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(to_candid_Listing_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(to_candid_Listing_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async declineOrderRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineOrderRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineOrderRequest(arg0);
            return result;
        }
    }
    async deleteListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async filterListingsByCategory(arg0: ProductCategory): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListingsByCategory(to_candid_ProductCategory_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListingsByCategory(to_candid_ProductCategory_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuyerOrderRequests(): Promise<Array<OrderRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerOrderRequests();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerOrderRequests();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmerOrderRequests(): Promise<Array<OrderRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmerOrderRequests();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmerOrderRequests();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingById(arg0: bigint): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingById(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingById(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsByFarmer(arg0: Principal): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsByFarmer(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsByFarmer(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsSorted(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsSorted(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsSorted(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderMessages(arg0: bigint): Promise<Array<OrderMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderMessages(arg0);
            return result;
        }
    }
    async getOrderRequestsForListing(arg0: bigint): Promise<Array<OrderRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderRequestsForListing(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderRequestsForListing(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrderRequest(arg0: bigint, arg1: number, arg2: string, arg3: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrderRequest(arg0, arg1, arg2, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrderRequest(arg0, arg1, arg2, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async publishListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishListing(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchListings(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async unpublishListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishListing(arg0);
            return result;
        }
    }
    async updateListing(arg0: bigint, arg1: Listing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, to_candid_Listing_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, to_candid_Listing_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Listing_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_OrderRequest_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderRequest): OrderRequest {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Listing | null {
    return value.length === 0 ? null : from_candid_Listing_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    contact: [] | [string];
    displayName: string;
    role: _UserRole;
    location: string;
}): {
    bio: string;
    contact?: string;
    displayName: string;
    role: UserRole;
    location: string;
} {
    return {
        bio: value.bio,
        contact: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.contact)),
        displayName: value.displayName,
        role: from_candid_UserRole_n18(_uploadFile, _downloadFile, value.role),
        location: value.location
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        accepted: null;
    } | {
        declined: null;
    };
    listingId: bigint;
    note: string;
    createdAt: _Time;
    updatedAt: [] | [_Time];
    message: [] | [string];
    quantity: number;
    buyer: Principal;
}): {
    id: bigint;
    status: Variant_pending_accepted_declined;
    listingId: bigint;
    note: string;
    createdAt: Time;
    updatedAt?: Time;
    message?: string;
    quantity: number;
    buyer: Principal;
} {
    return {
        id: value.id,
        status: from_candid_variant_n23(_uploadFile, _downloadFile, value.status),
        listingId: value.listingId,
        note: value.note,
        createdAt: value.createdAt,
        updatedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.updatedAt)),
        message: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.message)),
        quantity: value.quantity,
        buyer: value.buyer
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isPublished: boolean;
    availableQuantity: number;
    createdAt: _Time;
    unit: string;
    description: string;
    pricePerUnit: number;
    updatedAt: [] | [_Time];
    category: _ProductCategory;
    harvestDate: [] | [string];
    location: string;
    farmer: Principal;
}): {
    id: bigint;
    title: string;
    isPublished: boolean;
    availableQuantity: number;
    createdAt: Time;
    unit: string;
    description: string;
    pricePerUnit: number;
    updatedAt?: Time;
    category: ProductCategory;
    harvestDate?: string;
    location: string;
    farmer: Principal;
} {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        availableQuantity: value.availableQuantity,
        createdAt: value.createdAt,
        unit: value.unit,
        description: value.description,
        pricePerUnit: value.pricePerUnit,
        updatedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.updatedAt)),
        category: from_candid_ProductCategory_n11(_uploadFile, _downloadFile, value.category),
        harvestDate: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.harvestDate)),
        location: value.location,
        farmer: value.farmer
    };
}
function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grains: null;
} | {
    other: string;
} | {
    livestock: null;
} | {
    fruits: null;
} | {
    vegetables: null;
} | {
    dairy: null;
}): {
    __kind__: "grains";
    grains: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "livestock";
    livestock: null;
} | {
    __kind__: "fruits";
    fruits: null;
} | {
    __kind__: "vegetables";
    vegetables: null;
} | {
    __kind__: "dairy";
    dairy: null;
} {
    return "grains" in value ? {
        __kind__: "grains",
        grains: value.grains
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "livestock" in value ? {
        __kind__: "livestock",
        livestock: value.livestock
    } : "fruits" in value ? {
        __kind__: "fruits",
        fruits: value.fruits
    } : "vegetables" in value ? {
        __kind__: "vegetables",
        vegetables: value.vegetables
    } : "dairy" in value ? {
        __kind__: "dairy",
        dairy: value.dairy
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buyer: null;
} | {
    farmer: null;
}): UserRole {
    return "buyer" in value ? UserRole.buyer : "farmer" in value ? UserRole.farmer : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): Variant_pending_accepted_declined {
    return "pending" in value ? Variant_pending_accepted_declined.pending : "accepted" in value ? Variant_pending_accepted_declined.accepted : "declined" in value ? Variant_pending_accepted_declined.declined : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderRequest>): Array<OrderRequest> {
    return value.map((x)=>from_candid_OrderRequest_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Listing_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Listing): _Listing {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    contact?: string;
    displayName: string;
    role: UserRole;
    location: string;
}): {
    bio: string;
    contact: [] | [string];
    displayName: string;
    role: _UserRole;
    location: string;
} {
    return {
        bio: value.bio,
        contact: value.contact ? candid_some(value.contact) : candid_none(),
        displayName: value.displayName,
        role: to_candid_UserRole_n31(_uploadFile, _downloadFile, value.role),
        location: value.location
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isPublished: boolean;
    availableQuantity: number;
    createdAt: Time;
    unit: string;
    description: string;
    pricePerUnit: number;
    updatedAt?: Time;
    category: ProductCategory;
    harvestDate?: string;
    location: string;
    farmer: Principal;
}): {
    id: bigint;
    title: string;
    isPublished: boolean;
    availableQuantity: number;
    createdAt: _Time;
    unit: string;
    description: string;
    pricePerUnit: number;
    updatedAt: [] | [_Time];
    category: _ProductCategory;
    harvestDate: [] | [string];
    location: string;
    farmer: Principal;
} {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        availableQuantity: value.availableQuantity,
        createdAt: value.createdAt,
        unit: value.unit,
        description: value.description,
        pricePerUnit: value.pricePerUnit,
        updatedAt: value.updatedAt ? candid_some(value.updatedAt) : candid_none(),
        category: to_candid_ProductCategory_n5(_uploadFile, _downloadFile, value.category),
        harvestDate: value.harvestDate ? candid_some(value.harvestDate) : candid_none(),
        location: value.location,
        farmer: value.farmer
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    buyer: null;
} | {
    farmer: null;
} {
    return value == UserRole.buyer ? {
        buyer: null
    } : value == UserRole.farmer ? {
        farmer: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "grains";
    grains: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "livestock";
    livestock: null;
} | {
    __kind__: "fruits";
    fruits: null;
} | {
    __kind__: "vegetables";
    vegetables: null;
} | {
    __kind__: "dairy";
    dairy: null;
}): {
    grains: null;
} | {
    other: string;
} | {
    livestock: null;
} | {
    fruits: null;
} | {
    vegetables: null;
} | {
    dairy: null;
} {
    return value.__kind__ === "grains" ? {
        grains: value.grains
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "livestock" ? {
        livestock: value.livestock
    } : value.__kind__ === "fruits" ? {
        fruits: value.fruits
    } : value.__kind__ === "vegetables" ? {
        vegetables: value.vegetables
    } : value.__kind__ === "dairy" ? {
        dairy: value.dairy
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
