/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Listing {
  'id' : bigint,
  'title' : string,
  'isPublished' : boolean,
  'availableQuantity' : number,
  'createdAt' : Time,
  'unit' : string,
  'description' : string,
  'pricePerUnit' : number,
  'updatedAt' : [] | [Time],
  'category' : ProductCategory,
  'harvestDate' : [] | [string],
  'location' : string,
  'farmer' : Principal,
}
export interface OrderMessage {
  'author' : Principal,
  'orderId' : bigint,
  'message' : string,
  'timestamp' : Time,
}
export interface OrderRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'accepted' : null } |
    { 'declined' : null },
  'listingId' : bigint,
  'note' : string,
  'createdAt' : Time,
  'updatedAt' : [] | [Time],
  'message' : [] | [string],
  'quantity' : number,
  'buyer' : Principal,
}
export type ProductCategory = { 'grains' : null } |
  { 'other' : string } |
  { 'livestock' : null } |
  { 'fruits' : null } |
  { 'vegetables' : null } |
  { 'dairy' : null };
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'contact' : [] | [string],
  'displayName' : string,
  'role' : UserRole,
  'location' : string,
}
export type UserRole = { 'buyer' : null } |
  { 'farmer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOrderRequest' : ActorMethod<[bigint], undefined>,
  'addOrderMessage' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createListing' : ActorMethod<[Listing], bigint>,
  'declineOrderRequest' : ActorMethod<[bigint], undefined>,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'filterListingsByCategory' : ActorMethod<[ProductCategory], Array<Listing>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getBuyerOrderRequests' : ActorMethod<[], Array<OrderRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getFarmerOrderRequests' : ActorMethod<[], Array<OrderRequest>>,
  'getListingById' : ActorMethod<[bigint], [] | [Listing]>,
  'getListingsByFarmer' : ActorMethod<[Principal], Array<Listing>>,
  'getListingsSorted' : ActorMethod<[string], Array<Listing>>,
  'getOrderMessages' : ActorMethod<[bigint], Array<OrderMessage>>,
  'getOrderRequestsForListing' : ActorMethod<[bigint], Array<OrderRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrderRequest' : ActorMethod<
    [bigint, number, string, [] | [string]],
    bigint
  >,
  'publishListing' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<[string], Array<Listing>>,
  'unpublishListing' : ActorMethod<[bigint], undefined>,
  'updateListing' : ActorMethod<[bigint, Listing], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];