/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ProductCategory = IDL.Variant({
  'grains' : IDL.Null,
  'other' : IDL.Text,
  'livestock' : IDL.Null,
  'fruits' : IDL.Null,
  'vegetables' : IDL.Null,
  'dairy' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'availableQuantity' : IDL.Float64,
  'createdAt' : Time,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'updatedAt' : IDL.Opt(Time),
  'category' : ProductCategory,
  'harvestDate' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'farmer' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'buyer' : IDL.Null,
  'farmer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'contact' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'role' : UserRole,
  'location' : IDL.Text,
});
export const OrderRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  }),
  'listingId' : IDL.Nat,
  'note' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : IDL.Opt(Time),
  'message' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
  'buyer' : IDL.Principal,
});
export const OrderMessage = IDL.Record({
  'author' : IDL.Principal,
  'orderId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptOrderRequest' : IDL.Func([IDL.Nat], [], []),
  'addOrderMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createListing' : IDL.Func([Listing], [IDL.Nat], []),
  'declineOrderRequest' : IDL.Func([IDL.Nat], [], []),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'filterListingsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getBuyerOrderRequests' : IDL.Func([], [IDL.Vec(OrderRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getFarmerOrderRequests' : IDL.Func([], [IDL.Vec(OrderRequest)], ['query']),
  'getListingById' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getListingsByFarmer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getListingsSorted' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'getOrderMessages' : IDL.Func([IDL.Nat], [IDL.Vec(OrderMessage)], ['query']),
  'getOrderRequestsForListing' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OrderRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrderRequest' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'publishListing' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'unpublishListing' : IDL.Func([IDL.Nat], [], []),
  'updateListing' : IDL.Func([IDL.Nat, Listing], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProductCategory = IDL.Variant({
    'grains' : IDL.Null,
    'other' : IDL.Text,
    'livestock' : IDL.Null,
    'fruits' : IDL.Null,
    'vegetables' : IDL.Null,
    'dairy' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'availableQuantity' : IDL.Float64,
    'createdAt' : Time,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'updatedAt' : IDL.Opt(Time),
    'category' : ProductCategory,
    'harvestDate' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'farmer' : IDL.Principal,
  });
  const UserRole = IDL.Variant({ 'buyer' : IDL.Null, 'farmer' : IDL.Null });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'contact' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'role' : UserRole,
    'location' : IDL.Text,
  });
  const OrderRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'accepted' : IDL.Null,
      'declined' : IDL.Null,
    }),
    'listingId' : IDL.Nat,
    'note' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : IDL.Opt(Time),
    'message' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
    'buyer' : IDL.Principal,
  });
  const OrderMessage = IDL.Record({
    'author' : IDL.Principal,
    'orderId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptOrderRequest' : IDL.Func([IDL.Nat], [], []),
    'addOrderMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createListing' : IDL.Func([Listing], [IDL.Nat], []),
    'declineOrderRequest' : IDL.Func([IDL.Nat], [], []),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'filterListingsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getBuyerOrderRequests' : IDL.Func([], [IDL.Vec(OrderRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getFarmerOrderRequests' : IDL.Func([], [IDL.Vec(OrderRequest)], ['query']),
    'getListingById' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getListingsByFarmer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getListingsSorted' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
    'getOrderMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OrderMessage)],
        ['query'],
      ),
    'getOrderRequestsForListing' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OrderRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrderRequest' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'publishListing' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
    'unpublishListing' : IDL.Func([IDL.Nat], [], []),
    'updateListing' : IDL.Func([IDL.Nat, Listing], [], []),
  });
};

export const init = ({ IDL }) => { return []; };